[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "rgba(254, 248, 239,1)" # sepia yellow

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ebd2b9"  #wheat

# Color used for almost all text.
textColor = "#000000" #black 